{ 'ἀ': 'α',
  'ἁ': 'α',
  'ἂ': 'ὰ',
  'ἃ': 'ὰ',
  'ἄ': 'ά',
  'ἅ': 'ά',
  'ἆ': 'ᾶ',
  'ἐ': 'ε',
  'ἑ': 'ε',
  'ἓ': 'ὲ',
  'ἔ': 'έ',
  'ἕ': 'έ',
  'ἠ': 'η',
  'ἡ': 'η',
  'ἢ': 'ὴ',
  'ἣ': 'ὴ',
  'ἤ': 'ή',
  'ἥ': 'ή',
  'ἦ': 'ῆ',
  'ἧ': 'ῆ',
  'ἰ': 'ι',
  'ἱ': 'ι',
  'ἳ': 'ὶ',
  'ἴ': 'ί',
  'ἵ': 'ί',
  'ἶ': 'ῖ',
  'ἷ': 'ῖ',
  'ὀ': 'ο',
  'ὁ': 'ο',
  'ὂ': 'ὸ',
  'ὃ': 'ὸ',
  'ὄ': 'ό',
  'ὅ': 'ό',
  'ὐ': 'υ',
  'ὑ': 'υ',
  'ὒ': 'ὺ',
  'ὓ': 'ὺ',
  'ὔ': 'ύ',
  'ὕ': 'ύ',
  'ὖ': 'ῦ',
  'ὗ': 'ῦ',
  'ὠ': 'ω',
  'ὡ': 'ω',
  'ὢ': 'ὼ',
  'ὤ': 'ώ',
  'ὥ': 'ώ',
  'ὦ': 'ῶ',
  'ὧ': 'ῶ',
  'ᾄ': 'ά',
  'ᾅ': 'ά',
  'ᾐ': 'η',
  'ᾑ': 'η',
  'ᾔ': 'ή',
  'ᾖ': 'ῆ',
  'ᾗ': 'ῆ',
  'ᾠ': 'ω',
  'ᾧ': 'ῶ',
  'ᾳ': 'α',
  'ᾴ': 'ά',
  'ᾷ': 'ᾶ',
  '᾽': '',
  '－': '',
  'ῃ': 'η',
  'ῄ': 'ή',
  'ῇ': 'ῆ',
  'ῥ': 'ρ',
  'ῳ': 'ω',
  'ῴ': 'ώ',
  'ῷ': 'ῶ' }

let mappingsEff = Object.entries(mappings).map(([k, v]) => [new RegExp(k, 'g'), v])

let mx2 = s => mappingsEff.reduce((acc, [k, v]) => acc.replace(k, v), s)

const normalise = s => s.toLowerCase().normalize('NFKD').replace(/[\u0313\u0314\u0345-]/g, '').normalize('NFC')

[...new Set([].concat(...results.map(r => r.text).map(s => mx2(s.toLowerCase()).split(''))))].sort().join('').trim()


// a clause finding algorithm given a text
text.replace(/[’.,·]/g, '').split(' ').map(t => normalise(t)).filter(t => t).map(w => [w, clauses.filter(c => c.search.includes(w)).sort(() => Math.random() < 0.5 ? 1 : -1).sort((a, b) => a.search.length < b.search.length ? -1 : 1).slice(0, 5).map(c => c.text + '  |  ' + c.plain)])
